name: checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Ruff
        run: uv run ruff check .

      - name: Mypy
        run: uv run mypy src tests

      - name: Pytest
        run: uv run pytest
